PAGE_NUMBER_REGEX = r" (\d+)$"
DETECT_SPECIAL_CHARS = r"^\W+|\W+$"

DEFAULT_CHAR_MARGIN = 500.0
DEFAULT_LINE_MARGIN = 0.10

DEFAULT_HEADER_FONTSIZE_THRESHOLD = 0.23
DEFAULT_TOPIC_FONTSIZE_THRESHOLD = 0.01

DEFAULT_HEADER_INDENT_THRESHOLD = 0.23
DEFAULT_TOPIC_INDENT_THRESHOLD = 0.01